<?php
    $arr=array(
		["fname"=>"Стоян", "mname" => "Николаев", "lname"=>"Иванов", "falkNumber" => 23, "city"=>"Асеновград"],
		["fname" => "Георги", "mname" => "Петров", "lname" => "Иванов", "falkNumber" => 13, "city" => "Пловдив"],
		["fname" => "Васил", "mname" => "Георгиев", "lname" => "Петров", "falkNumber" => 43, "city" => "София"],
		["fname" => "Георги", "mname" => "Тодоров", "lname" => "Стоянов", "falkNumber" => 63, "city" => "София"],	
		["fname" => "Стоян", "mname" => "Иванов", "lname" => "Димитров", "falkNumber" => 53, "city" => "Пловдив"]
		);
?>