<!DOCTYPE HTML>  
<html>
<head>
<meta charset="utf-8">
<style>
	table {
		border-collapse: collapse;
		}
	td, th {
		border: 1px solid #dddddd;
		text-align: left;
		padding: 8px;
	}
	tr:nth-child(even) {
		background-color: #dddddd;
		}
	.error {color: #FF0000;}
	h3 {
		color: blue;
	}
</style>
</head>
<body>  
<h2>	
[ <a href="home.php" style="text-decoration:none;">Начало</a> ]
[ <a href="edit.php" style="text-decoration:none;">Редактиране</a> ]
[ <a href="delete.php" style="text-decoration:none;">Изтриване</a> ]
[ <a href="insert.php" style="text-decoration:none;">Нов запис</a> ]
</h2>
<br>